### PR TITLE
Create Get IBLI page.

### PR DESCRIPTION
**Pull request by nedSaf**
#168

### CODE REVIEW

**Comment by nedSaf** [comment]
@niryariv This is the page, Needs any changes ?
selection_031

**Comment by niryariv** [comment]
can push, if needed we'll change later according to IBLI feedback

**Comment by nedSaf** [comment]
Merged.

**Comment by nedSaf** [comment]
[Deployed](http://dev-ibli.gotpantheon.com/content/get-ibli)

**Comment by niryariv** [comment]
need to add a size for the APA image (if possible, same as the Takaful logo) - this is on FF/mac:

screen shot 2014-09-11 at 12 11 48 pm

**Comment by nedSaf** [comment]
@niryariv Fixed in FF/mac:
selection_036

**Comment by niryariv** [comment]
great, thanks!

**Comment by nedSaf** [comment]
Merged.

**Comment by nedSaf** [comment]
[Deployed](http://dev-ibli.gotpantheon.com/content/get-ibli)

**Pull request closed without merging**
