### PR TITLE
Welcome box

### PR DESCRIPTION
**Pull request by NofarGizra**
#62

### CODE REVIEW

**Comment by NofarGizra** [comment]
New title:

welcome1

**Comment by NofarGizra** [comment]
New video and description:

welcome2

**Comment by niryariv** [comment]
@NofarGizra please remove the text under the video - just need the video itself (it will be replaced later on anyway)

**Comment by NofarGizra** [comment]
Description removed:

welcome3

**Comment by NofarGizra** [comment]
Merged manually.

**Pull request closed without merging**
