### PR TITLE
Add legend to the map.

### PR DESCRIPTION
**Pull request by nedSaf**
#206

selection_028

@niryariv How does this look ?

### CODE REVIEW

**Comment by niryariv** [comment]
looks ok. is it possible to make the bg a little less transparent (ie the CSS opacity)?

**Comment by nedSaf** [comment]
@niryariv Is it better like this ?
selection_030

**Comment by niryariv** [comment]
excellent

**Comment by nedSaf** [comment]
Ok, pushing.

**Comment by nedSaf** [comment]
Merged.

**Pull request closed without merging**
