### PR TITLE
Rate Calculator

### PR DESCRIPTION
**Pull request by nedSaf**
#160

WIP: This is how it looks right now.

selection_043

selection_044

### CODE REVIEW

**Comment by niryariv** [comment]
instead of a "calculate button", just do the calculation whenever the value changes in any of the input boxes.

so, no need for a "Calculate" button, just text under the form saying "Your calculated rate is: **1234**"

**Comment by nedSaf** [comment]
Calculating on change:
selection_045

**Comment by niryariv** [comment]
1. why is the bg grey?
2. plz make sure all icons face right (to the input box)

**Comment by nedSaf** [comment]
Ya it's just screenshots i took, this is not the real icons yet, Still working on it.

**Comment by nedSaf** [comment]
@niryariv PR is ready.

Process:
Click on province popup will appear with new link:
selection_046

Click on Calculate your rate:
selection_047

Start putting a value in the calculator:
selection_048

Calculator with all values:
selection_049

**Comment by niryariv** [comment]
looks good

**Comment by nedSaf** [comment]
Merged.

**Comment by nedSaf** [comment]
[Deployed](http://dev-ibli.gotpantheon.com/)

**Pull request closed without merging**
