### PR TITLE
Subscription box

### PR DESCRIPTION
**Pull request by nedSaf**
#239

### CODE REVIEW

**Comment by nedSaf** [comment]
Update: The form is ready and saving in the database.
Now sending email to the user.

**Comment by nedSaf** [comment]
Update: Added sending mail, Have to check it in the office.

**Comment by nedSaf** [comment]
Update:
This is the form:
selection_078

The form can be submitted only once by an authenticated user or a guest (Locked by IP or cookie).

If the form is already submitted, It will look like this:
selection_080

This is the result admin page:
selection_079

The admin can download the results in csv or excel formats. Clear the results as well.

This is the mail that the subscriber receives: 
selection_077

Still working on changing the "From" email address to be "ibliwebsystem@cgiar.org".

@niryariv 
Is limiting the user to only one submission is correct ?
If yes, i want a sentence to write when the form is already submitted.

**Comment by niryariv** [comment]
@nader77 no need to limit the user to one submission. it's possible that an agent will demo this to users and will submit for them, so will have many submissions from the same browser.

**Comment by nedSaf** [comment]
Update: 
1- Unlimited the number of submissions.
2- Fixed email sender.

selection_081

**Comment by nedSaf** [comment]
Merged.

**Comment by nedSaf** [comment]
[Deployed](http://live-ibli.gotpantheon.com/)

**Comment by niryariv** [comment]
@nader77 what's the URL for viewing the subscriber list?

**Comment by nedSaf** [comment]
@niryariv When you are admin, You can edit the webform and see the result like this:
ibli

Or you can visit directly:
/node/41/webform-results/table

Admin only as well.

**Pull request closed without merging**
