### PR TITLE
Boxes below the map

### PR DESCRIPTION
**Pull request by NofarGizra**
#59

### CODE REVIEW

**Comment by NofarGizra** [comment]
Update:
We're having problems with the icons - they appear different from the icons in `getbootstrap.com`, and they don't look good at all... We need to find the problem and solve it.

**Comment by niryariv** [comment]
we can pick icons from Font Awesome instead - since we'd import all the icons there anyway in #85

**Comment by NofarGizra** [comment]
Update:
We are now using FA icons.

**Comment by NofarGizra** [comment]
below

**Comment by NofarGizra** [comment]
Merged.

**Pull request closed without merging**
