### PR TITLE
Adding premium rates page

### PR DESCRIPTION
**Pull request by bitamar**
#149

screen shot 2014-08-31 at 2 39 41 pm

### CODE REVIEW

**Comment by bitamar** [comment]
screen shot 2014-08-31 at 4 54 39 pm

**Comment by bitamar** [comment]
@apurbashee - What's the meaning of  the 10rate, 15rate... columns? How would you like them to be displayed?

**Comment by bnedavies** [comment]
@bitamar @niryariv Please only show 15rate.  All others can be removed.  Please change "15rate" to "Premium Rate"

**Comment by bnedavies** [comment]
The same applies to all previous years as well

**Comment by bitamar** [comment]
@nader77 ^^

**Comment by niryariv** [comment]
moved this to #197

**Pull request closed without merging**
