### PR TITLE
Additions to downloaded PDF

### PR DESCRIPTION
**Pull request by nedSaf**
#208

@niryariv Is it good like this ?
selection_026

### CODE REVIEW

**Comment by niryariv** [comment]
~~ok, good enough for now~~

**Comment by nedSaf** [comment]
Ok, Pushing to Dev.

**Comment by niryariv** [comment]
on second thought: 
- [x] use 24pt font, arial, not bold
- [x] add "Vegetation index for" to beginning of title

**Comment by nedSaf** [comment]
@niryariv How does this look ?
selection_027

**Comment by niryariv** [comment]
ok, ready to push

**Comment by nedSaf** [comment]
Merged.

**Pull request closed without merging**
