### PR TITLE
Fix the style and remove the date.

### PR DESCRIPTION
**Pull request by mldk-tech**
#125

### CODE REVIEW

**Comment by mldk-tech** [comment]
You can see that i remove the publish date, and make image as wide as the text.
whatis

**Comment by niryariv** [comment]
please also remove the thin grey line between the title and image:

whatis

**Comment by NofarGizra** [comment]
@niryariv 
Grey line was removed in another PR.

**Comment by NofarGizra** [comment]
Updated screenshot:
whatis2

**Comment by NofarGizra** [comment]
Merged.

**Pull request closed without merging**
