### PR TITLE
pull the RSS feed from the blog into the LAST UPDATES "news" tab 

### PR DESCRIPTION
**Pull request by mldk-tech**
#100

### CODE REVIEW

**Comment by nedSaf** [comment]
Update: Fixed importer settings, Still not importing the right data.

**Comment by nedSaf** [comment]
Update: Importing the news feed correctly, Need to import image and fix date.
selection_070

**Comment by nedSaf** [comment]
@niryariv PR is ready. 
This is how it looks now:
selection_071

**Comment by niryariv** [comment]
Ok, looks fine

**Comment by nedSaf** [comment]
Merged.

**Comment by nedSaf** [comment]
Deployed.

**Pull request closed without merging**
