### PR TITLE
Create installation profile, and move IDL data under a single directory.

### PR DESCRIPTION
**Pull request by amitaibu**
#29

### CODE REVIEW

**Comment by amitaibu** [comment]
@alanorth Hi! the PR places the Drupal distro in the root of the repo -- so .travis and all out installation scripts can find it there. I've moved all the previous data under the `IDL` folder. 

Let us know if we can go ahead an merge this to master.

**Comment by amitaibu** [comment]
Another option would actually be to have separate repos. 

@niryariv ^^

**Comment by alanorth** [comment]
@amitaibu Looks good to me, except there's more in the IDL folder than just IDL stuff (IDL + MATLAB scripts).  Maybe we could call that folder `dataprocessing` or something.

**Comment by niryariv** [comment]
yep - @amitaibu please rename to `dataprocessing`

**Comment by amitaibu** [comment]
Moved files under `dataProcessing`, and merged.

**Comment by amitaibu** [comment]
(Notice Travis configuration for automatic tests is already in place)

**Pull request closed without merging**
