### PR TITLE
Embed videos in the IBLI on the Ground items.

### PR DESCRIPTION
**Pull request by nedSaf**
#241

Clicking on the image:
selection_072

### CODE REVIEW

**Comment by niryariv** [comment]
what does the hover on the image look like?

**Comment by nedSaf** [comment]
Still working on it, Will update soon.

**Comment by nedSaf** [comment]
@niryariv Is it only clicking on the icon that will open the video and the rest of the picture and the title open the node ?
Or they all open the video ?

**Comment by niryariv** [comment]
for now all open the video

**Comment by nedSaf** [comment]
@niryariv This is how the icon looks like. 
a suggestion: Maybe we should change it to white because the pictures are dark most of the time.
ibli

**Comment by niryariv** [comment]
yes, please make it white

**Comment by nedSaf** [comment]
@niryariv Converted to white:
ibli

**Comment by niryariv** [comment]
looks good. is it possible to change the modal so that the "X" is on the top right corner, like so:

screen shot 2014-10-01 at 3 55 49 pm

(not critical - if it's not something that can be done quickly let me know)

**Comment by nedSaf** [comment]
Ok checking.

**Comment by nedSaf** [comment]
How does this look ? >>
ibli

**Comment by niryariv** [comment]
cool, just please move the "x" up & right a few pixels (the center of the "x" should be right on the top right corner of the modal)

**Comment by nedSaf** [comment]
Close button moved: 
selection_074

**Comment by niryariv** [comment]
looks ok

**Comment by nedSaf** [comment]
Merged.

**Pull request closed without merging**
