### PR TITLE
Changes to premiums table UI

### PR DESCRIPTION
**Pull request by nedSaf**
#197

Changes made:
- Showing all rates.
- Changed the title "IBLI_UNIT" to "UNIT". [Requested here](https://github.com/Gizra/IBLI/issues/197#issuecomment-54742195)
- Removed the column "DIVI_WOR". [Requested here](https://github.com/Gizra/IBLI/issues/197#issuecomment-54742195)
- Changed "rate" to "trigger".
- coloured all "15trigger" columns in light yellow.

selection_029

@niryariv PR is ready.

### CODE REVIEW

**Comment by niryariv** [comment]
@nader77 all ok - just add a space between the number and "trigger", eg "15 trigger"

**Comment by nedSaf** [comment]
@niryariv Fixed:
selection_032

**Comment by niryariv** [comment]
ok

**Comment by nedSaf** [comment]
Merged.

**Comment by nedSaf** [comment]
[Deployed](http://dev-ibli.gotpantheon.com/premium-rates)

**Pull request closed without merging**
